FROM ubuntu:22.04
RUN apt-get update && apt-get install -y build-essential git ffmpeg libsdl2-dev && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN git clone https://github.com/ggerganov/whisper.cpp .
RUN make
RUN bash ./models/download-ggml-model.sh medium
EXPOSE 8081
CMD ["./server", "-m", "models/ggml-medium.bin", "-l", "hi", "--port", "8081", "--host", "0.0.0.0"]
